apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.archiveadaptationservice.name }}
spec:
  replicas: {{ .Values.archiveadaptationservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.archiveadaptationservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.archiveadaptationservice.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.archiveadaptationname  }}
      containers:
      - name: adaptation-service
        image: {{ .Values.imagestore.archiveadaptationservice.repository }}:{{ .Values.imagestore.archiveadaptationservice.tag }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMQP_URL
          value: {{ .Values.archiveadaptationservice.amqpurl }}
        - name: INPUT_MOUNT
          value: {{ .Values.volumemountpath.source }}
        - name: OUTPUT_MOUNT
          value: {{ .Values.volumemountpath.target }}
        - name: ARCHIVE_PROCESSING_IMAGE
          value: {{ .Values.imagestore.archiveprocessingservice.repository }}:{{ .Values.imagestore.archiveprocessingservice.tag }}
        - name: ARCHIVE_PROCESSING_TIMEOUT
          value: {{ .Values.icapserviceconfig.processingtimeoutduration }}
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 0.5
            memory: 100Mi