kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswallsource-pv
  labels:
    type: local
spec:
  #storageClassName: azurefile
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/test-data"