apiVersion: v1
kind: Service
metadata:
  name: frontend-icap-lb
spec:
  type: LoadBalancer
  ports:
  - port: 1344
    targetPort: 1344
  - port: 1345
    targetPort: 1345
  selector:
    app: adaptation
