apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
spec:
  replicas: {{ .Values.icapservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.icapservice.applabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.icapservice.applabel }}     
    spec:
      containers:   
        - name: mvp-icap-service
          image: {{ .Values.imagestore.icapservice.repository }}:{{ .Values.imagestore.icapservice.tag }}
          ports:
            - containerPort: 1344
          envFrom:
          - configMapRef:
              name: icap-service-config
          volumeMounts:
            - name: source-vol
              mountPath: {{ .Values.volumemountpath.source }}
            - name: target-vol
              mountPath: {{ .Values.volumemountpath.target }}
        - name: monitoring-service
          image: pranaysahith/icap-monitoring:0.1
          env:
            - name: ELASTIC_HOST
              value: quickstart-es-http.monitoring.svc.cluster.local
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: ""
            - name: ICAP_HOST
              value: localhost
            
      volumes:
        - name: source-vol
          persistentVolumeClaim:
            claimName: glasswallsource-pvc
        - name: target-vol
          persistentVolumeClaim:
            claimName: glasswalltarget-pvc

