apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: {{ .Values.podjanitor.name }}
  name: {{ .Values.podjanitor.name }}
  namespace: {{ .Values.podjanitor.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
     metadata:
       labels:
         app: {{ .Values.podjanitor.name }}
     spec:
      template:
        metadata:
          labels:
            app: {{ .Values.podjanitor.name }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.janitorname }}
          containers:
          - name: pod-janitor
            image: glasswallsolutions/pod-janitor:main-latest
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 10Mi
          restartPolicy: OnFailure 