apiVersion: v1
kind: Service
metadata:
  name: policy-update-service
  labels:
    app: {{ .Values.policyupdateservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.policyupdateservice.applabel }}
  ports:
  - port: {{ .Values.policyupdateservice.port }}
    targetPort:  {{ .Values.policyupdateservice.port }}

