{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "policy-management-api.fullname" $root }}-configuration
data:
  {{- range $key, $value := .Values.configuration }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
