apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ncfspolicyupdateservice.name }}
  labels:
    app: {{ .Values.ncfspolicyupdateservice.applabel }}
spec:
  replicas: {{ .Values.ncfspolicyupdateservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ncfspolicyupdateservice.applabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.ncfspolicyupdateservice.applabel }}   
    spec:
      serviceAccountName: {{ .Values.serviceAccount.ncfspolicyupdatename }} 
      containers:    
      - name: ncfs-policy-update-service
        image: {{ .Values.imagestore.ncfspolicyupdateservice.registry}}{{ .Values.imagestore.ncfspolicyupdateservice.repository }}:{{ .Values.imagestore.ncfspolicyupdateservice.tag }}
        ports:
        - containerPort: {{ .Values.ncfspolicyupdateservice.port }}
        env:
        - name: NAMESPACE
          value: {{ .Values.referencencfsservice.namespace }}
        - name: LISTENING_PORT
          value: "{{ .Values.ncfspolicyupdateservice.port }}"
        - name: CONFIGMAP_NAME
          value: {{ .Values.referencencfsservice.configmapname }}
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: ncfspolicyupdateservicesecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ncfspolicyupdateservicesecret
              key: password 