apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.ncfspolicyupdateservice.rolename }}-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.ncfspolicyupdatename  }}
  namespace: {{ .Values.serviceAccount.namespace  }}
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: {{ .Values.ncfspolicyupdateservice.rolename }}
  apiGroup: rbac.authorization.k8s.io 