kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ncfspolicyupdateservice.rolename }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "create", "get"] 