apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ncfspolicyupdateservice.name }}
  labels:
    app: {{ .Values.ncfspolicyupdateservice.applabel }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.ncfspolicyupdateservice.applabel }}
  ports:
  - port: {{ .Values.ncfspolicyupdateservice.port }}
    targetPort:  {{ .Values.ncfspolicyupdateservice.port }}
