metadataName: "nginx-ingress-controller"
appLabel: "nginx-ingress"
replicaCount: 1

image:
  url: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1"

container:
  httpPort: 80
  httpsPort: 443
  metricsPort: 10254

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

service:
  httpPort: 80
  httpTargetPort: 80
  httpsPort: 443
  httpsTargetPort: 443
  type: LoadBalancer
  loadBalancerIP: 35.189.76.197


