apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ncfs-policy-update-service.fullname" . }}-service-account
  labels:
    environment: {{ .Values.environment | default "development" | quote }}