environment:
serviceAccount:
  name: adaptation-service-sa

volumemountpath:
  source: "/var/source"
  target: "/var/target"  
  
adaptationservice:
  name: adaptation-service
  namespace: icap-adaptation
  replicas: 1
  amqpurl: "amqp://guest:guest@rabbitmq-service:5672/"
  
icapservice:
  name: mvp-icap-service
  applabel: adaptation
  
icapserviceconfig:
  originalstorename: "original-store"
  outcomequeuename: "transaction-outcome"

  
